### ISSUE TITLE
Server crash MissingPaletteEntryException: Missing Palette entry for index 1.

### ISSUE THREAD

**Issue by XionioXMaster** [PurpurMC/Purpur#1193]
### Spark link

https://pastebin.com/1u6aaHcT

### Expected behavior

?

### Observed/Actual behavior

serve generation

### Steps/models to reproduce

I generated server for use chunky plugin

I'm use 
Terralith Data pack
[Arboria - Biome Enhancement](https://www.planetminecraft.com/data-pack/arboria-worldgen/)
Cavernous [1.19.x]

### Purpur version

[06:41:49 INFO]: Current: git-Purpur-1838 (MC: 1.19.2)*
Previous: git-petal-"d448170" (MC: 1.19.2)
* You are 7 version(s) behind

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Crash occurs suddenly, sometimes during world generation

Sometimes during world generation it is possible to reveal
https://mcpaste.com/7485dff9bbc208b2cf9967fc113d68a4

**Comment by BillyGalbreath** [comment]
Is this still a problem on 1.19.3?

**Comment by XionioXMaster** [comment]
> Is this still a problem on 1.19.3?

Idk

**Comment by BillyGalbreath** [comment]
Ok. Closing for now then. Let us know if you can recreate it on 1.19.3
